# Final Project Introduction and Brainstorming: Energy and Environment
Team Members: Zoe Jackson, Roy Pan, Aspen Scott-Lewis, Michael Williams

## **Step 1: Deciding on Data Sources**

As a group, decide on a theme (or related themes) that you want to explore as your final project topic. It should be a topic that is of relevance to you (e.g. a hobby you are very passionate about) or the world (e.g. climate change, food insecurity). Ideally, your topic should surround a modern local, national or global issue. Determine a handful of datasets that could be more rich when considered together. A good start would be to choose a "core" dataset and then finding 1-2 supporting sources. If you have an idea for a topic but can't find supporting data, ask Dr. Mendible for help!

Individually, each group member should download and investigate one unique data set. Answer the following questions about each one:

What is available in this data set? What are the variables (either a complete list or a summary of the theme)? How many observations are included?
Are there any challenges with this data set? Does it need to be cleaned, manipulated, or reshaped to be useful? Are these manipulations straightforward or will they take longer?
How will this data be merged or used with the rest of the data?
Then, share in your groups what you found. Make a team decision on what data you will be using for the final project.

In [ ]:
!pip install vega_datasets
!pip install pycountry
!pip install pycountry_convert

Requirement already satisfied: vega_datasets in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from vega_datasets) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->vega_datasets) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->vega_datasets) (1.17.0)
Collecting pycountry
  Downloading pycountry-26.2.16-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-26.2.16-py3-none-any.whl (8.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 55.0 MB/s eta 0:00:00
Installing collected packages: pycountry
Successfully installed pycountry-26.2.16
Collecting pycountry_convert
  Downloading pycountry_convert-0.7.2-py3-none-any.whl.metadata (7.2 kB)
Collecting pprintpp>=0.3.0 (from pycountry_convert)
  Downloading pprintpp-0.4.0-py2.py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: pycountry>=16.11.27.1 in /usr/local/lib/python3.12/dist-packages (from pycountry_convert) (26.2.16)
Requirement already satisfied: pytest>=3.4.0 in /usr/local/lib/python3.12/dist-packages (from pycountry_convert) (8.4.2)
Collecting pytest-mock>=1.6.3 (from pycountry_convert)
  Downloading pytest_mock-3.15.1-py3-none-any.whl.metadata (3.9 kB)
Collecting pytest-cov>=2.5.1 (from pycountry_convert)
  Downloading pytest_cov-7.0.0-py3-none-any.whl.metadata (31 kB)
Collecting repoze.lru>=0.7 (from pycountry_convert)
  Downloading repoze.lru-0.7-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: wheel>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from pycountry_convert) (0.46.3)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=3.4.0->pycountry_convert) (2.3.0)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from pytest>=3.4.0->pycountry_convert) (26.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=3.4.0->pycountry_convert) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=3.4.0->pycountry_convert) (2.19.2)
Collecting coverage>=7.10.6 (from coverage[toml]>=7.10.6->pytest-cov>=2.5.1->pycountry_convert)
  Downloading coverage-7.13.4-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (8.5 kB)
Downloading pycountry_convert-0.7.2-py3-none-any.whl (13 kB)
Downloading pprintpp-0.4.0-py2.py3-none-any.whl (16 kB)
Downloading pytest_cov-7.0.0-py3-none-any.whl (22 kB)
Downloading pytest_mock-3.15.1-py3-none-any.whl (10 kB)
Downloading repoze.lru-0.7-py3-none-any.whl (10 kB)
Downloading coverage-7.13.4-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (254 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 254.1/254.1 kB 7.8 MB/s eta 0:00:00
Installing collected packages: repoze.lru, pprintpp, coverage, pytest-mock, pytest-cov, pycountry_convert
Successfully installed coverage-7.13.4 pprintpp-0.4.0 pycountry_convert-0.7.2 pytest-cov-7.0.0 pytest-mock-3.15.1 repoze.lru-0.7

In [ ]:
import pandas as pd
import altair as alt
from vega_datasets import data as vega_data
import pycountry
import pycountry_convert

import os
import requests

In [ ]:
def load_remote_file_if_not_exists(filename: str, url: str) -> None:
  if not os.path.exists(filename):
    resp = requests.get(url)
    with open(filename, "wb") as f:
      f.write(resp.content)

Michael Williams

Dataset: EI-Stats-Review-ALL-data.xlsx
Sheet Name: Gas Production = bcf

What is available in this data set?

This dataset has numerical data on gas production in individual countries and geographical regions.

What are the variables (either a complete list or a summary of the theme)?

There are over 70 fields which relate to either a country region, or aggregated total. Each entry is related to one year, so there is a year field that is unlabelled initially.

Are there any challenges with this data set? Does it need to be cleaned, manipulated, or reshaped to be useful? Are these manipulations straightforward or will they take longer?

Yes. The data is in .xlsx format, which is more complex than a plain csv. It is a multi-sheet dataset, which I am focusing on one sheet for my portion of this assignment. Additionally, the tables needed to be transposed since they were row-based fields and not column-based. The data needed to be cleaned. There were several blank rows that needed to be removed, as well as the dataset being transposed. I also needed to restrict the rows being read to avoid loading in notes and titles.

How will this data be merged or used with the rest of the data?

This data will likely be merged with data on renewable energy to see if there is a relationship with historical gas production and historical renewable energy production.

In [ ]:
ei_stats_filename = "EI-Stats-Review-ALL-data.xlsx"
load_remote_file_if_not_exists(ei_stats_filename, "https://github.com/roy-y-2023/data3310/raw/refs/heads/main/data/EI-Stats-Review-ALL-data.xlsx")

def load_ei_stats_sheet(sheet_name: str, first_row: int, last_row: int) -> pd.DataFrame:
  if first_row >= last_row:
    print("first row cannot be >= last_row")
    return None

  df = (pd.read_excel(
      ei_stats_filename,
      nrows=last_row - first_row + 1,
      skiprows=first_row - 1,
      sheet_name=sheet_name,
    )
    .dropna(how="all")
    .transpose()
    .dropna(how="all")
  )
  df.columns = df.iloc[0]
  df = df.iloc[1:]
  df = df.reset_index()
  return df

gas_prod_df = load_ei_stats_sheet("Gas Production - bcf", 3, 78)
gas_prod_df.columns.values[0] = "Year"
gas_prod_df

Billion cubic feet per day,Year,Canada,Mexico,US,Total North America,Argentina,Bolivia,Brazil,Colombia,Peru,...,Myanmar,Pakistan,Thailand,Vietnam,Other Asia Pacific,Total Asia Pacific,Total World,of which: OECD,Non-OECD,European Union #
0,1970,5.22621,1.06721,55.290406,61.583825,0.566433,0.004051,0.007847,0.120875,0.03846,...,0.000713,0.281588,0.0,0.0,0.525912,1.461123,94.438953,70.107078,24.331875,8.996448
1,1971,5.713719,1.056361,56.857632,63.627711,0.612114,0.004051,0.012457,0.125822,0.04591,...,0.001378,0.255049,0.0,0.0,0.590658,1.745461,101.021051,74.345144,26.675907,10.52695
2,1972,6.433347,1.09495,56.518416,64.046713,0.580274,0.107727,0.016922,0.153276,0.04402,...,0.001469,0.270063,0.0,0.0,0.63906,2.01488,105.707308,77.336351,28.370957,12.222587
3,1973,6.911757,1.193016,56.621722,64.726494,0.633614,0.166534,0.019421,0.159255,0.04321,...,0.001782,0.309177,0.0,0.0,0.663062,2.506907,111.097952,79.870906,31.227047,13.885929
4,1974,6.768361,1.250642,54.127914,62.146918,0.681977,0.174298,0.03737,0.165693,0.044513,...,0.015946,0.35458,0.0,0.0,0.698081,3.065124,113.443245,79.148117,34.295128,15.165113
5,1975,6.9136,1.271234,50.121807,58.306642,0.723754,0.171823,0.040705,0.144314,0.054943,...,0.017111,0.368395,0.0,0.0,0.686101,3.418554,113.685117,75.856785,37.828331,15.77579
6,1976,6.955368,1.243297,49.5776,57.776265,0.688184,0.176628,0.046756,0.14616,0.059437,...,0.0237,0.374639,0.0,0.0,0.760338,3.939433,118.263344,76.452813,41.810531,16.737576
7,1977,7.326462,1.32215,49.930353,58.578964,0.712275,0.186901,0.05836,0.16617,0.05918,...,0.021864,0.410405,0.0,0.0,0.861195,4.817076,123.593137,77.936716,45.65642,16.951096
8,1978,7.070266,1.655035,49.725934,58.451235,0.734857,0.1842,0.0768,0.220676,0.061835,...,0.025666,0.421715,0.0,0.0,0.825935,5.726962,127.77716,78.370769,49.406391,16.486141
9,1979,7.455482,2.009111,51.234482,60.699074,0.680284,0.201416,0.084156,0.252098,0.057178,...,0.025666,0.475035,0.0,0.0,0.737221,6.511709,136.392162,81.515068,54.877094,16.559747
10,1980,6.872653,2.423323,50.665034,59.96101,0.787789,0.246313,0.09811,0.268669,0.061294,...,0.03318,0.578475,0.0,0.0,0.753879,6.926403,137.817284,80.373796,57.443488,15.916748
11,1981,6.659247,2.61792,50.271895,59.549062,0.821939,0.263417,0.088276,0.295279,0.070588,...,0.039925,0.632573,0.02637,0.000934,0.72342,6.994222,140.590873,79.62376,60.967113,15.626744
12,1982,6.99009,2.791533,46.749827,56.53145,0.921159,0.273206,0.126136,0.314794,0.07408,...,0.042777,0.689932,0.134404,0.001774,0.754738,7.270198,141.234309,75.428727,65.805583,14.444288
13,1983,6.574463,2.815127,42.346035,51.735625,1.236366,0.262291,0.170569,0.345847,0.048797,...,0.057036,0.680238,0.158223,0.006115,0.791888,8.207834,142.49759,71.273721,71.223869,14.819699
14,1984,7.186049,2.761429,45.830363,55.777841,1.264892,0.251588,0.19798,0.350645,0.065752,...,0.060672,0.696104,0.235555,0.005307,0.867549,9.524995,154.271162,75.662334,78.608828,14.965779
15,1985,7.7899,2.686214,43.333629,53.809743,1.306935,0.250026,0.249036,0.358637,0.051405,...,0.087455,0.712553,0.310491,0.003314,0.948821,10.353501,158.774131,74.676296,84.097835,15.174059
16,1986,7.30628,2.386072,42.211831,51.904183,1.459364,0.25464,0.290035,0.349533,0.054524,...,0.101713,0.764258,0.36224,0.003455,0.996108,11.421753,162.880721,72.275543,90.605178,14.323287
17,1987,7.919823,2.425305,43.730306,54.075434,1.425491,0.266342,0.323973,0.36833,0.054198,...,0.113121,0.818386,0.506101,0.003455,0.993859,12.151585,171.044613,75.133392,95.911221,14.430114
18,1988,9.120722,2.450146,44.788599,56.359467,1.685272,0.280764,0.325142,0.354215,0.050986,...,0.098592,0.865296,0.598213,0.002607,1.039882,12.945345,178.095545,76.387824,101.707721,13.439695
19,1989,9.716557,2.358485,45.54593,57.620972,1.786803,0.296949,0.334271,0.358976,0.043349,...,0.103615,0.925026,0.599248,0.003081,0.797053,13.595627,184.768175,78.676077,106.092098,13.888274
20,1990,10.008832,2.552925,46.768023,59.32978,1.678598,0.303475,0.304336,0.379715,0.041487,...,0.0808,0.988041,0.653066,0.003735,0.770756,14.440494,190.574979,80.64666,109.928319,13.797117
21,1991,10.534273,2.58901,46.519411,59.642694,1.87525,0.301675,0.316387,0.375995,0.038926,...,0.081751,1.067214,0.809347,0.006722,0.787232,15.711314,193.11496,82.573239,110.541721,14.451091
22,1992,11.575173,2.502664,46.764807,60.842644,1.88514,0.27317,0.357431,0.38411,0.035012,...,0.082476,1.044156,0.861096,0.019553,0.807235,16.568793,193.153255,84.183247,108.970008,14.215741
23,1993,12.777525,2.687611,47.426133,62.891269,2.024856,0.273295,0.419854,0.377081,0.03697,...,0.104565,1.205362,0.971837,0.023342,0.801049,17.593599,195.887979,87.522626,108.365352,14.559291
24,1994,13.83049,2.827399,49.375786,66.033675,2.095425,0.294691,0.458527,0.388989,0.038553,...,0.135935,1.228791,1.074299,0.023342,0.782316,19.177944,198.753985,91.441017,107.312968,14.072554
25,1995,14.778098,2.823843,48.697551,66.299492,2.353236,0.294453,0.506063,0.407802,0.037343,...,0.155897,1.260298,1.137433,0.013585,0.761854,20.153702,202.053083,92.775252,109.277831,14.268371
26,1996,14.85127,2.97232,49.231349,67.054939,2.714639,0.296538,0.551503,0.438717,0.037798,...,0.151679,1.365621,1.311308,0.026723,0.820659,21.943749,211.308685,96.90644,114.402245,15.211351
27,1997,15.454364,3.009629,49.492764,67.956757,2.576234,0.250632,0.601961,0.548974,0.022443,...,0.14354,1.365323,1.618694,0.049577,0.857347,23.427457,211.723214,97.795538,113.927676,14.091762
28,1998,16.022611,3.186458,50.052781,69.26185,2.784177,0.261764,0.630567,0.62788,0.038088,...,0.167304,1.438032,1.75738,0.08403,0.797782,23.812665,213.084821,94.967176,118.117645,13.459608
29,1999,16.500191,3.312348,49.357131,69.16967,3.252754,0.210766,0.740401,0.550802,0.038274,...,0.163502,1.640003,1.925045,0.121376,0.857001,25.30321,223.524879,99.94205,123.58283,12.901444
30,2000,17.011312,3.220646,50.038781,70.270739,3.510357,0.301275,0.743896,0.553437,0.032087,...,0.322319,1.732203,2.016123,0.148978,0.898629,26.771094,231.6842,101.862229,129.821971,12.52862
31,2001,17.359259,3.206446,51.46217,72.027874,3.49457,0.439943,0.76181,0.574612,0.034456,...,0.665415,1.833895,1.966444,0.186732,0.954445,27.622224,237.855717,104.332316,133.523402,12.815369
32,2002,17.485361,3.263242,49.462661,70.211264,3.397655,0.563665,0.920365,0.580387,0.041161,...,0.798498,1.988201,2.055452,0.224079,1.086426,29.421204,243.391068,103.242139,140.14893,12.636975
33,2003,17.032987,3.370897,50.103844,70.507728,3.861528,0.647796,0.999851,0.556325,0.048704,...,0.91257,2.472063,2.149634,0.221558,1.055172,31.276343,252.103511,103.73198,148.371531,12.25198
34,2004,17.052852,3.572671,48.544161,69.169684,4.211302,0.908907,1.096663,0.591937,0.079868,...,0.966956,2.959928,2.233467,0.387342,1.01884,33.228344,259.979299,103.63107,156.348228,13.268525
35,2005,17.333447,4.287286,47.354622,68.975355,4.293409,1.124417,1.087637,0.6237,0.141256,...,1.159724,3.155117,2.372153,0.601278,1.093042,35.994278,266.864924,102.874572,163.990352,12.501488
36,2006,17.357147,4.687872,48.543057,70.588075,4.337632,1.204113,1.110571,0.6545,0.165316,...,1.197748,3.223743,2.435286,0.653563,1.406162,37.68732,275.93936,104.009576,171.929783,12.336093
37,2007,16.900642,4.533684,50.494055,71.928381,4.218136,1.289729,1.11824,0.702218,0.249157,...,1.285202,3.270259,2.602951,0.661032,1.668476,39.383687,283.249089,104.32889,178.920199,11.616815
38,2008,16.064466,4.557191,52.68904,73.310697,4.134358,1.330766,1.38712,0.841267,0.33751,...,1.175515,3.339224,2.875148,0.69824,1.754109,41.130242,292.62125,106.899829,185.721421,12.239551
39,2009,15.001555,5.087542,53.947502,74.036598,3.899241,1.149573,1.187825,0.978344,0.346935,...,1.09837,3.357473,2.84353,0.747863,1.788872,43.383579,284.529781,106.51189,178.017891,11.382068
40,2010,14.47331,4.951582,55.647921,75.072813,3.773057,1.326912,1.453276,1.049125,0.707739,...,1.181143,3.420046,3.26202,0.877829,1.727685,46.857003,304.260318,109.255183,195.005135,12.14873
41,2011,14.616528,5.040708,59.730983,79.388219,3.649296,1.454577,1.666752,1.020337,1.110771,...,1.214246,3.419199,3.270611,0.791745,1.715031,48.337477,315.806728,111.366149,204.440579,11.363908
42,2012,14.502671,4.90644,62.632853,82.041964,3.540266,1.62674,1.913635,1.112088,1.153812,...,1.207173,3.531199,3.709956,0.871054,1.706396,50.017698,322.434275,114.526394,207.907881,10.99402
43,2013,14.698674,5.078349,63.439911,83.216934,3.343365,1.893946,2.123678,1.279404,1.199646,...,1.244328,3.443008,3.767034,0.910413,1.763647,50.083069,326.084843,115.748328,210.336515,11.022546
44,2014,15.382835,4.963384,68.184049,88.530268,3.336595,1.976269,2.258946,1.193233,1.270092,...,1.600595,3.38505,3.782248,0.953269,2.234025,52.673486,333.326766,120.105331,213.221435,9.667738
45,2015,15.553513,4.638987,71.626186,91.818686,3.433857,1.944111,2.303144,1.123327,1.224569,...,1.859262,3.39094,3.626019,0.995283,2.703883,55.218918,340.103906,123.836959,216.266947,8.154385
46,2016,15.924042,4.431653,70.181245,90.53694,3.597306,1.823578,2.327639,1.157097,1.352613,...,1.763811,3.346082,3.596471,0.987908,2.796845,56.87285,342.879789,124.550831,218.328958,7.94638
47,2017,16.570653,4.055155,72.284503,92.91031,3.594345,1.798967,2.629871,1.137081,1.258822,...,1.722087,3.352619,3.477915,0.921151,2.822067,59.647346,356.468312,128.807006,227.661306,7.427452
48,2018,17.1036,3.849293,81.362677,102.315569,3.814302,1.67686,2.434521,1.197442,1.239543,...,1.642055,3.308946,3.360032,0.934595,2.603631,61.633977,373.073228,138.834886,234.238341,6.673122
49,2019,16.411831,3.733317,89.797068,109.942216,4.02638,1.460478,2.491041,1.220844,1.305752,...,1.788171,3.163171,3.461097,0.952335,2.772294,64.486891,384.353563,146.837825,237.515738,5.898911
50,2020,15.979692,3.484719,89.233487,108.697898,3.694775,1.417652,2.338519,1.201763,1.274298,...,1.689205,2.95141,3.155315,0.852897,2.799145,63.492676,373.116355,144.398122,228.718233,4.617763
51,2021,16.675221,3.322269,91.37847,111.37596,3.735468,1.465771,2.354247,1.215835,1.203028,...,1.661593,3.160075,3.050214,0.696512,2.632386,65.996429,391.51618,146.970956,244.545224,4.288102
52,2022,17.881826,3.493585,95.852761,117.228172,4.029978,1.315693,2.225566,1.202854,1.446948,...,1.629847,2.769859,2.452052,0.754399,2.312354,66.759647,391.8821,154.721713,237.160387,3.950708
53,2023,18.366157,3.72815,99.946309,122.040616,4.024262,1.142386,2.266211,1.166951,1.492402,...,1.465846,2.684146,2.483826,0.69717,2.083281,66.864999,393.223271,157.505544,235.717727,3.3347
54,2024,18.734042,3.450804,99.672682,121.857527,4.256412,1.148836,2.203649,1.070579,1.540001,...,1.424991,2.517258,2.754108,0.588458,1.862748,68.268725,397.960702,156.485097,241.475605,3.186002
55,2024.1,0.020031,-0.074392,-0.002738,-0.0015,0.057688,0.005646,-0.027606,-0.082585,0.031894,...,-0.027872,-0.062175,0.108817,-0.155933,-0.105858,0.020993,0.012048,-0.006479,0.024427,-0.044591
56,2014-24,0.019905,-0.035695,0.038698,0.032467,0.024646,-0.052801,-0.002475,-0.010788,0.019456,...,-0.011554,-0.029185,-0.031225,-0.047094,-0.018011,0.026273,0.017881,0.026812,0.012521,-0.105064
57,2024.2,0.047075,0.008671,0.250459,0.306205,0.010696,0.002887,0.005537,0.00269,0.00387,...,0.003581,0.006325,0.006921,0.001479,0.004681,0.171546,1.0,0.393217,0.606783,0.008006

Zoe Jackson

Dataset: 'number-of-people-with-and-without-electricity-access.csv'

What is available in this data set?

>In this data set we are able to use numerical data of populations of people with and without electricity from different countries.

What are the variables (either a complete list or a summary of the theme)? How many observations are included? Are there any challenges with this data set?

>The variables include: Entity(Countries), Year, With Electricity, Without electricity,

Does it need to be cleaned, manipulated, or reshaped to be useful?

>Because there are so many countries, to be useful, it would be best if we fliter down to a specific set of coutries.

Are these manipulations straightforward or will they take longer?

>The manipulations are straightfoward.

How will this data be merged or used with the rest of the data?

>This data could be merged with our larger data set ("EI-Stats-Review-ALL-data.xlsx") by possibly layering energy production trends from different countries.
Are these manipulations straightforward or will they take longer?
>The manipulations are pretty straightfoward in regards to filtering down to individual countries.

In [ ]:
#df = pd.read_csv('number-of-people-with-and-without-electricity-access.csv')
df = pd.read_csv('https://raw.githubusercontent.com/AspenSL04/Data3310/refs/heads/main/number-of-people-with-and-without-electricity-access.csv')
df.head()

        Entity Code  Year  With electricity  Without electricity
0  Afghanistan  AFG  2000          885734.4           19244592.0
1  Afghanistan  AFG  2001         1886440.6           18397866.0
2  Afghanistan  AFG  2002         3014314.5           18363804.0
3  Afghanistan  AFG  2003         4319279.5           18413770.0
4  Afghanistan  AFG  2004         5607435.5           17953218.0

Aspen Scott-Lewis
EI stats review dataset, focusing on Renewable power generation (incl hydro) page, and the Renewable Energy: generation by source page

This has data by country and year, as well as some slightly processed data, such as percent growth or share of renewable energy growth

The dataset is in xls and isn't in the ideal format for altair, but they should be fairly straighforward either in excel or in pandas

This is a very rich dataset that we can likely use for most of our plots. We might add some supplementary datasets for additional context or to highlight an idea we find interesting.

Roy Pan

Dataset: [Energy consumption by source and country](https://ourworldindata.org/grapher/energy-consumption-by-source-and-country)

As its name suggets, it contains different countries for different years for several energy sources (e.g. Solar, Wind, Hydropower, Nuclear, Gas, Coal, Oil). While it contains many data, it doesn't include every country (and some of them on there is blank), so the challenges have been to map the missing ones to a default value like the continent they're on.

In [ ]:
# For Visualization 3
energy_consumption_by_source_and_country_filename = "energy-consumption-by-source-and-country.csv"
load_remote_file_if_not_exists(energy_consumption_by_source_and_country_filename, "https://raw.githubusercontent.com/roy-y-2023/data3310/refs/heads/main/data/energy-consumption-by-source-and-country.csv")
energy_consumption_by_source_and_country_df = pd.read_csv(energy_consumption_by_source_and_country_filename)
energy_consumption_by_source_and_country_df.head()

,Entity,Code,Year,Other renewables,Biofuels,Solar,Wind,Hydropower,Nuclear,Gas,Coal,Oil
0,Africa,NaN,1965,0.0,0.0,0.0,0.0,38.626762,0.0,9.571930,323.49615,341.07257
1,Africa,NaN,1966,0.0,0.0,0.0,0.0,43.083344,0.0,10.698092,323.12222,369.46457
2,Africa,NaN,1967,0.0,0.0,0.0,0.0,44.973988,0.0,10.573844,330.29160,368.28156
3,Africa,NaN,1968,0.0,0.0,0.0,0.0,52.606503,0.0,10.717145,343.51288,389.57162
4,Africa,NaN,1969,0.0,0.0,0.0,0.0,61.391357,0.0,12.520175,346.64288,397.37260

In [ ]:
CLEAN_ENERGY_SOURCE_NAMES = ["Other renewables", "Biofuels", "Solar", "Wind", "Hydropower", "Nuclear"]
energy_consumption_by_source_and_country_df["Total_Conventional_Energy"] = energy_consumption_by_source_and_country_df["Gas"] + energy_consumption_by_source_and_country_df["Coal"] + energy_consumption_by_source_and_country_df["Oil"]
energy_consumption_by_source_and_country_df["Total_Clean_Energy"] = energy_consumption_by_source_and_country_df["Other renewables"] + energy_consumption_by_source_and_country_df["Biofuels"] + energy_consumption_by_source_and_country_df["Solar"] + energy_consumption_by_source_and_country_df["Wind"] + energy_consumption_by_source_and_country_df["Hydropower"] + energy_consumption_by_source_and_country_df["Nuclear"]
energy_consumption_by_source_and_country_df["Total"] = energy_consumption_by_source_and_country_df["Total_Conventional_Energy"] + energy_consumption_by_source_and_country_df["Total_Clean_Energy"]
energy_consumption_by_source_and_country_df["Clean_Energy_Share"] = energy_consumption_by_source_and_country_df["Total_Clean_Energy"] / energy_consumption_by_source_and_country_df["Total"] * 100
energy_consumption_by_source_and_country_df_2024 = energy_consumption_by_source_and_country_df[energy_consumption_by_source_and_country_df["Year"] == 2024]

energy_consumption_by_source_and_country_df_valid = energy_consumption_by_source_and_country_df_2024.dropna(subset=["Clean_Energy_Share"])
code_to_share = energy_consumption_by_source_and_country_df_valid.set_index("Code")["Clean_Energy_Share"].to_dict()
code_to_entity = energy_consumption_by_source_and_country_df_valid.set_index("Code")["Entity"].to_dict()
entity_to_share = energy_consumption_by_source_and_country_df.set_index("Entity")["Clean_Energy_Share"].to_dict()

def get_continent_share(alpha_2: str) -> float | None:
    try:
        continent_code = pycountry_convert.country_alpha2_to_continent_code(alpha_2)
        continent_name = pycountry_convert.convert_continent_code_to_continent_name(continent_code)
        return entity_to_share.get(continent_name) if continent_name else None
    except Exception:
        return 0

rows = []
for country in pycountry.countries:
    alpha_3 = country.alpha_3
    alpha_2 = country.alpha_2

    if alpha_3 in code_to_share:
        entity = code_to_entity[alpha_3]
        share = code_to_share[alpha_3]
    else:
        entity = country.name
        share = get_continent_share(alpha_2)

    rows.append({"Entity": entity, "Code_Num": int(country.numeric), "Clean_Energy_Share": share})

all_countries_energy_consumption_by_source_df = pd.DataFrame(rows)
all_countries_energy_consumption_by_source_df = all_countries_energy_consumption_by_source_df[all_countries_energy_consumption_by_source_df["Entity"] != "Antarctica"]
all_countries_energy_consumption_by_source_df.head()

          Entity  Code_Num  Clean_Energy_Share
0          Aruba       533           20.261376
1    Afghanistan         4           15.011216
2         Angola        24            9.665484
3       Anguilla       660           20.261376
4  Åland Islands       248           26.247755

## **Step 2: Visualization Brainstorming**

Then as a group, brainstorm a list of at least 5 visualizations that could be made with this collective information. Come up with a one-sentence statement or question that the graphic would address. For each of the visualizations, answer the following questions. Your answer can be in the form of a mock-up if you have ready-to-plot data.

What variables would you use to show this?
Do you need to compute new variables, filter, or do other manipulations to show this?
What chart type (line, scatter, bar, etc) would be most effective to show this?
Which encodings would you map to which variables?
What other design considerations (color, scales, titles, labels, ticks) would you need to make? If you don't know yet, that's ok, but give a best guess.
Compile your answers into a single notebook and submit it here.

In [ ]:
alt.Chart(gas_prod_df).mark_circle().encode(
    x = alt.X("Year:N", title=None),
    y = alt.Y("US:Q", title="US Gas Production (Billion cubic feet per day)")
).transform_filter(
    "datum.Year"
)

alt.Chart(...)

A plot representing the amount of electricity produced over time and number of people wihtout electricity. This would be the most effective when done on a single country or a very selective number of countries. So filtering down to the country level. This would be represented as a line plot, with two lines. One line representing the amount of electricity produced, and the other being numbr of people with/without electricity for each year. The variables needed include:
>Entity:N (countries)

>Years:O

>With electricity:Q

>Without Electricity:Q

In [ ]:
countries = ['United States', 'Uruguay', 'Nigeria', 'China']

def country_plot(country):
    country_df = df[df['Entity'] == country]

    withE = alt.Chart(country_df).mark_line().encode(
        x=alt.X('Year:O', title='Year'),
        y=alt.Y('With electricity:Q', title='Population'),
    )

    withoutE = alt.Chart(country_df).mark_line(strokeDash=[5,5]).encode(
        x='Year:O',
        y='Without electricity:Q',
    )

    return (withE + withoutE).properties(
        title=country,
        width=300,
        height=200
    )


c1 = country_plot(countries[0])
c2 = country_plot(countries[1])
c3 = country_plot(countries[2])
c4 = country_plot(countries[3])

(c1 | c2) & (c3 | c4)

alt.VConcatChart(...)

In [ ]:
dfASL = pd.read_csv('https://raw.githubusercontent.com/AspenSL04/Data3310/refs/heads/main/consolidated-edata-sheets.csv')
c1 = alt.Chart(dfASL).mark_bar().encode(
    alt.X('2014-24 renew gen growth', title='% Renewable Energy Generation Growth 2014-2024').axis(format='.0%'),
    alt.Y('Terawatt-hours renew gen', title='Country').sort('-x')
).transform_window(
    rank='rank(2014-24 renew gen growth)',
sort=[alt.SortField('2014-24 renew gen growth', order='descending')]
).transform_filter(
    (alt.datum.rank < 20)
)

c2 = alt.Chart(dfASL).mark_bar().encode(
    alt.X('Total source 24 growth', title = '% Growth in Renewable Energy Sources in 2024').axis(format='.0%'),
    alt.Y('Terawatt-hours source 23', title='Country').sort('-x')
).transform_window(
    rank='rank(Total source 24 growth)',
sort=[alt.SortField('Total source 24 growth', order='descending')]
).transform_filter(
    (alt.datum.rank < 20)
)

c1 | c2

alt.HConcatChart(...)

These two charts show the top twenty countries growing their renewable energy generation and renewable energy sources. These were quick to plot but other charts showing data not already provided by the dataset will require more processing. They also reveal that the dataset includes some grouped entities (such as Other Southern Africa) that will need processing to show seperately or exclude
-Aspen

Visualization 3:

I'm using the share of clean energy for a given country as percentage, computed from the raw values, that's neccessary for showing on Choropleths and other types of charts in general as different country have different baseline that will cause many smaller countries to have nearly zero.

Alternatively it can be shown as bar chart. Although the Choropleths chart isn't good at showing precise values, but it does show off geographical relationship of these values, that countries next to each other might have similar share of clean energy, and some regions have high share of clean energy.

One sentence statement: North Europe has the highest share of energy being clean energy, while Africa in general has the lowest.

In [ ]:
countries = alt.topo_feature(vega_data.world_110m.url, 'countries')

alt.Chart(countries).mark_geoshape().encode(
    alt.Color("Clean_Energy_Share:Q", bin=alt.Bin(maxbins=10)),
    tooltip='Entity:N'
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(all_countries_energy_consumption_by_source_df, 'Code_Num', ["Clean_Energy_Share", "Entity"])
).project(
    "naturalEarth1"
).properties(
    title='Share of Clean Energy (2024)',
    width=800,
    height=500
)

alt.Chart(...)

## Stage 2

### Which clean energy grows the fastest?

In [ ]:
continent_entity_names = ["Africa", ]
world_energy_consumption_by_source_df = energy_consumption_by_source_and_country_df[energy_consumption_by_source_and_country_df["Entity"] == "World"]
world_energy_consumption_by_source_df

,Entity,Code,Year,Other renewables,Biofuels,Solar,Wind,Hydropower,Nuclear,Gas,Coal,Oil,Total_Conventional_Energy,Total_Clean_Energy,Total,Clean_Energy_Share
8143,World,OWID_WRL,1965,56.203850,9.029861,0.000000,0.000000,2564.4390,70.943670,6303.8210,16177.694,18011.457,40492.9720,2700.616381,43193.588381,6.252355
8144,World,OWID_WRL,1966,61.893772,9.209844,0.000000,0.000000,2732.8247,95.648020,6868.8145,16359.431,19426.414,42654.6595,2899.576336,45554.235836,6.365108
8145,World,OWID_WRL,1967,62.458030,9.383716,0.000000,0.000000,2793.7288,113.905594,7374.0580,16095.518,20778.916,44248.4920,2979.476140,47227.968140,6.308711
8146,World,OWID_WRL,1968,69.125140,9.553800,0.000000,0.000000,2942.4685,144.758770,8044.3477,16333.144,22510.490,46887.9817,3165.906210,50053.887910,6.324996
8147,World,OWID_WRL,1969,72.681140,9.723982,0.000000,0.000000,3115.9512,171.620590,8833.4340,16847.000,24445.395,50125.8290,3369.976912,53495.805912,6.299516
8148,World,OWID_WRL,1970,80.318430,13.501495,0.000000,0.000000,3262.9155,219.096250,9614.8090,17087.006,26684.725,53386.5400,3575.831675,56962.371675,6.277533
8149,World,OWID_WRL,1971,87.150920,13.562147,0.000000,0.000000,3409.0059,304.733830,10293.1900,16987.656,28116.584,55397.4300,3814.452797,59211.882797,6.442039
8150,World,OWID_WRL,1972,93.402420,14.823111,0.000000,0.000000,3568.4138,422.708740,10861.7140,17168.227,30335.396,58365.3370,4099.348071,62464.685071,6.562665
8151,World,OWID_WRL,1973,100.299540,14.250557,0.000000,0.000000,3619.4802,566.393250,11377.8330,17683.570,32730.184,61791.5870,4300.423547,66092.010547,6.506722
8152,World,OWID_WRL,1974,107.153390,14.334716,0.000000,0.000000,3975.6433,740.555800,11659.8590,17696.432,32230.395,61586.6860,4837.687206,66424.373206,7.283000
8153,World,OWID_WRL,1975,108.787750,13.688392,0.000000,0.000000,4024.6760,1027.356100,11659.7360,18045.436,31996.514,61701.6860,5174.508242,66876.194242,7.737444
8154,World,OWID_WRL,1976,121.222030,13.751190,0.000000,0.000000,4008.7126,1201.865000,12354.1390,18699.785,34061.470,65115.3940,5345.550820,70460.944820,7.586544
8155,World,OWID_WRL,1977,127.787630,18.318535,0.000000,0.000000,4143.5340,1495.966100,12759.8380,19267.412,35194.340,67221.5900,5785.606265,73007.196265,7.924707
8156,World,OWID_WRL,1978,135.302030,23.178776,0.000000,0.008333,4484.3950,1738.317600,13293.9470,19467.492,36709.973,69471.4120,6381.201739,75852.613739,8.412633
8157,World,OWID_WRL,1979,145.310180,28.023214,0.000000,0.016667,4708.8500,1807.944200,14118.0290,20370.578,37177.996,71666.6030,6690.144261,78356.747261,8.538058
8158,World,OWID_WRL,1980,155.367080,32.786120,0.000000,0.029167,4810.1367,1977.567100,14236.9610,20877.783,35568.645,70683.3890,6975.886167,77659.275167,8.982683
8159,World,OWID_WRL,1981,167.144290,29.747923,0.000000,0.029167,4913.6206,2335.418700,14395.8740,21158.002,34289.960,69843.8360,7445.960680,77289.796680,9.633821
8160,World,OWID_WRL,1982,192.840480,37.556244,0.000000,0.051389,5002.5225,2533.826400,14469.7310,21395.428,33270.010,69135.1690,7766.797013,76901.966013,10.099608
8161,World,OWID_WRL,1983,213.609150,49.019240,0.008333,0.091097,5216.0244,2871.702000,14703.8270,22050.973,33097.430,69852.2300,8350.454220,78202.684220,10.677964
8162,World,OWID_WRL,1984,238.581730,57.806427,0.017531,0.124321,5392.7036,3484.912400,15902.6760,23008.440,33623.600,72534.7160,9174.146009,81708.862009,11.227847
8163,World,OWID_WRL,1985,245.945560,68.410095,0.032632,0.178389,5497.8990,4135.893000,16262.2180,23996.738,33684.684,73943.6400,9948.358676,83891.998676,11.858531
8164,World,OWID_WRL,1986,267.010560,84.202995,0.042177,0.385643,5572.4250,4429.821300,16421.1070,24263.818,34710.477,75395.4020,10353.887675,85749.289675,12.074605
8165,World,OWID_WRL,1987,285.987580,85.330120,0.029453,0.542713,5647.7563,4818.703000,17281.8930,25228.488,35508.195,78018.5760,10838.349166,88856.925166,12.197529
8166,World,OWID_WRL,1988,294.252840,89.560200,0.028322,0.921055,5828.7466,5253.470000,18088.8440,25983.080,36641.938,80713.8620,11466.979017,92180.841017,12.439655
8167,World,OWID_WRL,1989,327.101140,95.689240,0.728398,7.360490,5798.8525,5402.807000,18888.6480,26231.049,37215.688,82335.3850,11632.538768,93967.923768,12.379266
8168,World,OWID_WRL,1990,366.326080,106.569110,1.078472,10.090196,5996.1724,5557.211000,19481.1500,25928.912,37906.816,83316.8780,12037.447258,95354.325258,12.623913
8169,World,OWID_WRL,1991,382.072500,110.646830,1.403397,11.350296,6134.8447,5823.082500,19972.8380,25686.727,37876.832,83536.3970,12463.400223,95999.797223,12.982736
8170,World,OWID_WRL,1992,409.874730,108.705635,1.296053,13.146699,6134.2070,5867.285600,20063.4820,25584.300,38404.773,84052.5550,12534.515717,96587.070717,12.977426
8171,World,OWID_WRL,1993,423.377660,114.340060,1.546326,15.844913,6503.6680,6069.345700,20265.4820,25708.832,38246.242,84220.5560,13128.122659,97348.678659,13.485671
8172,World,OWID_WRL,1994,439.616970,124.101776,1.658286,19.810360,6544.1816,6183.274000,20389.6130,25815.188,39068.176,85272.9770,13312.642992,98585.619992,13.503636
8173,World,OWID_WRL,1995,458.257400,131.070400,1.774674,22.978119,6898.3022,6451.471000,21104.4920,25999.217,39666.370,86770.0790,13963.853793,100733.932793,13.862115
8174,World,OWID_WRL,1996,470.949070,125.784515,1.942305,25.598890,6991.1523,6685.041500,22159.2540,26617.482,40576.630,89353.3660,14300.468580,103653.834580,13.796372
8175,World,OWID_WRL,1997,504.411650,130.030650,2.082377,33.411713,7114.8765,6639.067000,22030.3930,26563.252,41652.086,90245.7310,14423.879890,104669.610890,13.780389
8176,World,OWID_WRL,1998,525.679400,133.383960,2.255144,44.247944,7169.2590,6753.319000,22434.0000,26395.965,41788.617,90618.5820,14628.144448,105246.726448,13.898907
8177,World,OWID_WRL,1999,552.025200,135.247360,2.514689,58.963604,7223.5240,7010.293000,23071.9040,26508.807,42435.785,92016.4960,14982.567853,106999.063852,14.002522
8178,World,OWID_WRL,2000,577.878200,132.508770,2.939253,87.248740,7351.8926,7168.520500,23994.2580,27456.373,43016.630,94467.2610,15320.988063,109788.249063,13.955035
8179,World,OWID_WRL,2001,600.235400,131.424940,3.928208,106.022120,7123.2290,7330.212000,24316.8320,27880.072,43398.320,95595.2240,15295.051668,110890.275668,13.792960
8180,World,OWID_WRL,2002,646.155600,149.314600,4.923327,143.511750,7194.9185,7386.150000,25051.9280,28982.217,43697.090,97731.2350,15524.973777,113256.208777,13.707835
8181,World,OWID_WRL,2003,682.598630,168.931660,6.137612,172.437620,7146.9575,7197.058600,25727.7340,31519.594,44610.883,101858.2110,15374.121622,117232.332622,13.114233
8182,World,OWID_WRL,2004,737.757000,201.200490,8.043655,232.028170,7632.8750,7483.358400,26781.6200,33708.973,46413.184,106903.7770,16295.262715,123199.039715,13.226777
8183,World,OWID_WRL,2005,798.361270,234.475200,11.242224,281.256070,7825.9550,7442.488000,27439.2250,36200.953,47016.887,110657.0650,16593.777764,127250.842764,13.040211
8184,World,OWID_WRL,2006,850.215500,294.601960,15.387916,356.959400,8080.8350,7494.947800,28171.7090,38087.040,47436.953,113695.7020,17092.947576,130788.649576,13.069137
8185,World,OWID_WRL,2007,922.815100,391.652200,20.759594,456.129240,8171.3030,7303.106000,29338.2850,40241.703,48087.520,117667.5080,17265.765134,134933.273134,12.795780
8186,World,OWID_WRL,2008,987.290300,535.942140,33.458040,584.201660,8579.4010,7222.835000,30050.7460,40796.645,47692.652,118540.0430,17943.128140,136483.171140,13.146770
8187,World,OWID_WRL,2009,1056.993700,600.635500,55.273674,726.502140,8520.5610,7083.252000,29403.6050,40219.008,46633.970,116256.5830,18043.218014,134299.801014,13.435030
8188,World,OWID_WRL,2010,1182.440800,678.900760,88.336430,902.106930,8932.5850,7209.022500,31592.8710,42016.016,48192.543,121801.4300,18993.392420,140794.822420,13.490121
8189,World,OWID_WRL,2011,1240.742900,717.312100,170.319930,1142.296600,9048.1250,6871.570300,32349.8850,43983.350,48578.273,124911.5080,19190.366830,144101.874830,13.317222
8190,World,OWID_WRL,2012,1339.847900,746.395140,261.639100,1368.069200,9385.1390,6367.377400,33246.4380,44098.684,49362.210,126707.3320,19468.467740,146175.799740,13.318530
8191,World,OWID_WRL,2013,1441.806400,818.510440,354.499940,1626.221000,9687.9640,6368.981000,33733.2660,44745.465,49922.812,128401.5430,20297.982780,148699.525780,13.650335
8192,World,OWID_WRL,2014,1569.092200,865.945600,502.021480,1797.047200,9895.8580,6465.966300,33976.3550,44912.370,50336.395,129225.1200,21095.930780,150321.050780,14.033917
8193,World,OWID_WRL,2015,1669.679100,898.433170,649.451900,2105.701200,9820.6720,6519.849600,34780.0430,43695.344,51294.030,129769.4170,21663.786970,151433.203970,14.305837
8194,World,OWID_WRL,2016,1709.845300,938.653260,824.157700,2418.754600,10090.3380,6566.975600,35583.9840,42767.824,52314.516,130666.3240,22548.724460,153215.048460,14.717043
8195,World,OWID_WRL,2017,1800.717800,957.890870,1114.711300,2856.328400,10171.0450,6592.505000,36603.0550,43226.340,53263.332,133092.7270,23493.198370,156585.925370,15.003391
8196,World,OWID_WRL,2018,1952.103800,1038.815400,1431.774800,3162.158700,10419.3920,6716.976000,38317.0600,43897.330,53792.790,136007.1800,24721.220700,160728.400700,15.380742
8197,World,OWID_WRL,2019,2038.120200,1127.313600,1748.829300,3520.443800,10501.5490,6920.192400,39053.1800,43627.613,53997.266,136678.0590,25856.448300,162534.507300,15.908282
8198,World,OWID_WRL,2020,2152.289800,1068.229600,2116.744100,3940.164600,10763.2800,6639.518000,38704.0470,42316.324,49101.246,130121.6170,26680.226100,156801.843100,17.015250
8199,World,OWID_WRL,2021,2317.554200,1128.119400,2593.081300,4582.781200,10575.5320,6903.326700,40225.7340,44642.164,51846.820,136714.7180,28100.394800,164815.112800,17.049647
8200,World,OWID_WRL,2022,2379.479500,1193.131200,3249.745600,5184.601600,10650.5950,6583.330600,40059.6520,44926.926,53562.110,138548.6880,29240.883500,167789.571500,17.427116
8201,World,OWID_WRL,2023,2411.358400,1319.216300,4026.581800,5665.208000,10392.0800,6677.130000,40151.2200,45319.086,54838.684,140308.9900,30491.574500,170800.564500,17.852151
8202,World,OWID_WRL,2024,2476.356700,1366.878300,5150.569300,6124.465300,10860.7530,6871.835000,41278.2700,45850.543,55292.082,142420.8950,32850.857600,175271.752600,18.742813

In [ ]:
world_energy_consumption_by_source_and_year_df = world_energy_consumption_by_source_df.melt(
    id_vars=['Year'],
    value_vars=CLEAN_ENERGY_SOURCE_NAMES,
    var_name='Clean Energy Source',
    value_name='Energy Consumption'
)
world_energy_consumption_by_source_and_year_df

     Year Clean Energy Source  Energy Consumption
0    1965    Other renewables           56.203850
1    1966    Other renewables           61.893772
2    1967    Other renewables           62.458030
3    1968    Other renewables           69.125140
4    1969    Other renewables           72.681140
..    ...                 ...                 ...
355  2020             Nuclear         6639.518000
356  2021             Nuclear         6903.326700
357  2022             Nuclear         6583.330600
358  2023             Nuclear         6677.130000
359  2024             Nuclear         6871.835000

[360 rows x 3 columns]

In [ ]:
world_energy_consumption_by_source_and_year_df = world_energy_consumption_by_source_and_year_df.sort_values(['Clean Energy Source', 'Year'])
world_energy_consumption_by_source_and_year_df["Amount Chnage"] = world_energy_consumption_by_source_and_year_df.groupby("Clean Energy Source")["Energy Consumption"].diff()
world_energy_consumption_by_source_and_year_df["Percent Change"] = world_energy_consumption_by_source_and_year_df.groupby("Clean Energy Source")["Energy Consumption"].pct_change() * 100
# world_energy_consumption_by_source_and_year_df = world_energy_consumption_by_source_and_year_df.dropna()  # Remove NaN rows (first year of each group)
world_energy_consumption_by_source_and_year_df

,Year,Clean Energy Source,Energy Consumption,Amount Chnage,Percent Change
60,1965,Biofuels,9.029861,NaN,NaN
61,1966,Biofuels,9.209844,0.179983,1.993198
62,1967,Biofuels,9.383716,0.173872,1.887893
63,1968,Biofuels,9.553800,0.170084,1.812544
64,1969,Biofuels,9.723982,0.170182,1.781302
...,...,...,...,...,...
235,2020,Wind,3940.164600,419.720800,11.922383
236,2021,Wind,4582.781200,642.616600,16.309385
237,2022,Wind,5184.601600,601.820400,13.132209
238,2023,Wind,5665.208000,480.606400,9.269881
239,2024,Wind,6124.465300,459.257300,8.106627

In [ ]:
world_energy_consumption_by_source_and_year_base = alt.Chart(world_energy_consumption_by_source_and_year_df).encode(
    x=alt.X("Year:O", title="Year"),
    y=alt.Y("Energy Consumption:Q", title="Energy Consumption (TWh)"),
    color=alt.Color("Clean Energy Source:N", title="Source", legend=alt.Legend(orient="right", offset=100))
)

world_energy_consumption_by_source_and_year_lines = world_energy_consumption_by_source_and_year_base.mark_line().encode(
    tooltip=["Year", "Clean Energy Source", "Energy Consumption"]
)
world_energy_consumption_by_source_and_year_labels = world_energy_consumption_by_source_and_year_base.mark_text(align="left", dx=5).encode(
    text="Clean Energy Source:N"
).transform_filter(
    alt.datum.Year == 2024
)

(world_energy_consumption_by_source_and_year_lines + world_energy_consumption_by_source_and_year_labels).properties(
    title="Global Clean Energy Consumption Over Time (1965-2024)",
    width=800,
    height=400,
    padding={"left": 5, "top": 5, "right": 120, "bottom": 5}
)

alt.LayerChart(...)

Observations:
- Hydropower has been and steady increase over the years
- Nuclear reachs its peak arounf 2000 and staggering since then.
- Wind and Solar is exponentially increasing in the past two decades.

In [ ]:
change_of_world_energy_consumption_by_source_and_year_base = alt.Chart(world_energy_consumption_by_source_and_year_df).encode(
    x=alt.X('Year:O', title='Year'),
    y=alt.Y('Percent Change:Q', title='Year-over-Year Growth (%)', scale=alt.Scale(domain=[-20, 100], clamp=True)),
    color=alt.Color('Clean Energy Source:N', legend=alt.Legend(orient="right", offset=100))
)

change_of_world_energy_consumption_by_source_and_year_lines = change_of_world_energy_consumption_by_source_and_year_base.mark_line().encode(
    tooltip=['Year', 'Clean Energy Source', 'Percent Change']
)

change_of_world_energy_consumption_by_source_and_year_labels_right = change_of_world_energy_consumption_by_source_and_year_base.mark_text(align='left', dx=5).encode(
    text='Clean Energy Source:N'
).transform_filter(
    alt.datum.Year == 2024
)

(change_of_world_energy_consumption_by_source_and_year_lines + change_of_world_energy_consumption_by_source_and_year_labels_right).properties(
    title='Global Clean Energy Growth Rates (%)',
    width=800,
    height=400,
    padding={'left': 5, 'top': 5, 'right': 120, 'bottom': 5}
)

alt.LayerChart(...)

- The changes for each energy source is rather wild
- In recent year, solar and wind seems to be the clear winners in terms of increases.

### Change of clean energy share vs. life expectancy